export interface SupportedPlatform {
  id: string;
  name: string;
  category: 'video' | 'audio' | 'photo' | 'social' | 'other';
  exampleDomain: string;
  groupedExtractors: string[];
}

/**
 * Curated list of public media platforms supported by yt-dlp.
 * Strictly excludes YouTube and all YouTube-related extractors.
 * Groups internal extractors, clips, stories, albums, and variants under their primary platform.
 */
export const SUPPORTED_PLATFORMS: SupportedPlatform[] = [
  {
    id: 'tiktok',
    name: 'TikTok',
    category: 'video',
    exampleDomain: 'tiktok.com',
    groupedExtractors: ['tiktok', 'tiktok:collection', 'tiktok:user', 'tiktok:sound'],
  },
  {
    id: 'instagram',
    name: 'Instagram',
    category: 'photo',
    exampleDomain: 'instagram.com',
    groupedExtractors: ['instagram', 'instagram:story', 'instagram:tag', 'instagram:user'],
  },
  {
    id: 'twitter',
    name: 'Twitter / X',
    category: 'social',
    exampleDomain: 'x.com',
    groupedExtractors: ['twitter', 'twitter:card', 'twitter:broadcast', 'twitter:spaces', 'x'],
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    category: 'photo',
    exampleDomain: 'pinterest.com',
    groupedExtractors: ['pinterest', 'PinterestCollection'],
  },
  {
    id: 'reddit',
    name: 'Reddit',
    category: 'social',
    exampleDomain: 'reddit.com',
    groupedExtractors: ['reddit'],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    category: 'social',
    exampleDomain: 'facebook.com',
    groupedExtractors: ['facebook', 'facebook:ads', 'facebook:reel', 'facebook:watch'],
  },
  {
    id: 'threads',
    name: 'Threads',
    category: 'social',
    exampleDomain: 'threads.net',
    groupedExtractors: ['threads'],
  },
  {
    id: 'soundcloud',
    name: 'SoundCloud',
    category: 'audio',
    exampleDomain: 'soundcloud.com',
    groupedExtractors: ['soundcloud', 'soundcloud:playlist', 'soundcloud:track', 'soundcloud:user'],
  },
  {
    id: 'bluesky',
    name: 'Bluesky',
    category: 'social',
    exampleDomain: 'bsky.app',
    groupedExtractors: ['bluesky'],
  },
  {
    id: 'vimeo',
    name: 'Vimeo',
    category: 'video',
    exampleDomain: 'vimeo.com',
    groupedExtractors: ['vimeo', 'vimeo:album', 'vimeo:channel', 'vimeo:user', 'vimeo:review'],
  },
  {
    id: 'dailymotion',
    name: 'Dailymotion',
    category: 'video',
    exampleDomain: 'dailymotion.com',
    groupedExtractors: ['dailymotion', 'dailymotion:playlist', 'dailymotion:user'],
  },
  {
    id: 'twitch',
    name: 'Twitch',
    category: 'video',
    exampleDomain: 'twitch.tv',
    groupedExtractors: ['twitch:stream', 'twitch:clips', 'twitch:vod', 'twitch:collection'],
  },
  {
    id: 'kick',
    name: 'Kick',
    category: 'video',
    exampleDomain: 'kick.com',
    groupedExtractors: ['kick:clips', 'kick:live', 'kick:vod'],
  },
  {
    id: 'rumble',
    name: 'Rumble',
    category: 'video',
    exampleDomain: 'rumble.com',
    groupedExtractors: ['rumble', 'RumbleChannel', 'RumbleEmbed'],
  },
  {
    id: 'bilibili',
    name: 'Bilibili',
    category: 'video',
    exampleDomain: 'bilibili.com',
    groupedExtractors: ['BiliBili', 'BilibiliAudio', 'BilibiliAudioAlbum', 'bilibili:channel'],
  },
  {
    id: 'douyin',
    name: 'Douyin',
    category: 'video',
    exampleDomain: 'douyin.com',
    groupedExtractors: ['douyin'],
  },
  {
    id: 'xiaohongshu',
    name: 'Xiaohongshu',
    category: 'photo',
    exampleDomain: 'xiaohongshu.com',
    groupedExtractors: ['xiaohongshu'],
  },
  {
    id: 'weibo',
    name: 'Weibo',
    category: 'social',
    exampleDomain: 'weibo.com',
    groupedExtractors: ['weibo', 'WeiboUser', 'WeiboVideo'],
  },
  {
    id: 'likee',
    name: 'Likee',
    category: 'video',
    exampleDomain: 'likee.video',
    groupedExtractors: ['likee', 'likee:user'],
  },
  {
    id: 'snapchat',
    name: 'Snapchat',
    category: 'video',
    exampleDomain: 'snapchat.com',
    groupedExtractors: ['SnapchatSpotlight'],
  },
  {
    id: 'tumblr',
    name: 'Tumblr',
    category: 'social',
    exampleDomain: 'tumblr.com',
    groupedExtractors: ['tumblr'],
  },
  {
    id: 'vk',
    name: 'VK (VKontakte)',
    category: 'social',
    exampleDomain: 'vk.com',
    groupedExtractors: ['vk', 'vk:uservideos', 'vk:wallpost', 'vk:clip'],
  },
  {
    id: 'bandcamp',
    name: 'Bandcamp',
    category: 'audio',
    exampleDomain: 'bandcamp.com',
    groupedExtractors: ['bandcamp', 'Bandcamp:album', 'Bandcamp:user', 'Bandcamp:weekly'],
  },
  {
    id: 'mixcloud',
    name: 'Mixcloud',
    category: 'audio',
    exampleDomain: 'mixcloud.com',
    groupedExtractors: ['mixcloud', 'mixcloud:playlist', 'mixcloud:user'],
  },
  {
    id: 'audiomack',
    name: 'Audiomack',
    category: 'audio',
    exampleDomain: 'audiomack.com',
    groupedExtractors: ['audiomack', 'audiomack:album'],
  },
  {
    id: 'applepodcasts',
    name: 'Apple Podcasts',
    category: 'audio',
    exampleDomain: 'podcasts.apple.com',
    groupedExtractors: ['ApplePodcasts'],
  },
  {
    id: 'iheart',
    name: 'iHeartRadio',
    category: 'audio',
    exampleDomain: 'iheart.com',
    groupedExtractors: ['iheartradio', 'iheartradio:podcast'],
  },
  {
    id: 'spreaker',
    name: 'Spreaker',
    category: 'audio',
    exampleDomain: 'spreaker.com',
    groupedExtractors: ['spreaker', 'spreaker:show'],
  },
  {
    id: 'loom',
    name: 'Loom',
    category: 'video',
    exampleDomain: 'loom.com',
    groupedExtractors: ['loom', 'loom:folder'],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'social',
    exampleDomain: 'linkedin.com',
    groupedExtractors: ['linkedin', 'linkedin:events', 'linkedin:learning'],
  },
  {
    id: 'streamable',
    name: 'Streamable',
    category: 'video',
    exampleDomain: 'streamable.com',
    groupedExtractors: ['streamable'],
  },
  {
    id: 'imgur',
    name: 'Imgur',
    category: 'photo',
    exampleDomain: 'imgur.com',
    groupedExtractors: ['imgur', 'imgur:album', 'imgur:gallery'],
  },
  {
    id: '9gag',
    name: '9GAG',
    category: 'photo',
    exampleDomain: '9gag.com',
    groupedExtractors: ['9gag'],
  },
  {
    id: 'flickr',
    name: 'Flickr',
    category: 'photo',
    exampleDomain: 'flickr.com',
    groupedExtractors: ['flickr', 'flickr:album'],
  },
  {
    id: 'newgrounds',
    name: 'Newgrounds',
    category: 'video',
    exampleDomain: 'newgrounds.com',
    groupedExtractors: ['newgrounds', 'Newgrounds:playlist', 'Newgrounds:user'],
  },
  {
    id: 'peertube',
    name: 'PeerTube',
    category: 'video',
    exampleDomain: 'peertube.tv',
    groupedExtractors: ['peertube', 'PeerTube:Playlist'],
  },
  {
    id: 'coub',
    name: 'Coub',
    category: 'video',
    exampleDomain: 'coub.com',
    groupedExtractors: ['coub'],
  },
  {
    id: 'odysee',
    name: 'Odysee / LBRY',
    category: 'video',
    exampleDomain: 'odysee.com',
    groupedExtractors: ['lbry', 'lbry:channel', 'lbry:playlist'],
  },
  {
    id: 'bitchute',
    name: 'BitChute',
    category: 'video',
    exampleDomain: 'bitchute.com',
    groupedExtractors: ['bitchute', 'bitchute:channel'],
  },
  {
    id: 'rutube',
    name: 'Rutube',
    category: 'video',
    exampleDomain: 'rutube.ru',
    groupedExtractors: ['rutube', 'rutube:channel', 'rutube:playlist', 'rutube:movie'],
  },
  {
    id: 'wistia',
    name: 'Wistia',
    category: 'video',
    exampleDomain: 'wistia.com',
    groupedExtractors: ['wistia', 'wistia:playlist'],
  },
  {
    id: 'steam',
    name: 'Steam',
    category: 'video',
    exampleDomain: 'store.steampowered.com',
    groupedExtractors: ['steam', 'SteamCommunity', 'SteamCommunityBroadcast'],
  },
  {
    id: 'ted',
    name: 'TED',
    category: 'video',
    exampleDomain: 'ted.com',
    groupedExtractors: ['TedEmbed', 'TedPlaylist', 'TedSeries'],
  },
  {
    id: 'archive',
    name: 'Internet Archive',
    category: 'other',
    exampleDomain: 'archive.org',
    groupedExtractors: ['archive.org'],
  },
  {
    id: 'bbc',
    name: 'BBC',
    category: 'video',
    exampleDomain: 'bbc.co.uk',
    groupedExtractors: ['bbc', 'bbc:iplayer'],
  },
  {
    id: 'cnn',
    name: 'CNN',
    category: 'video',
    exampleDomain: 'cnn.com',
    groupedExtractors: ['cnn', 'cnn:article', 'cnn:live'],
  },
  {
    id: 'espn',
    name: 'ESPN',
    category: 'video',
    exampleDomain: 'espn.com',
    groupedExtractors: ['espn', 'espn:article'],
  },
  {
    id: 'arte',
    name: 'Arte.tv',
    category: 'video',
    exampleDomain: 'arte.tv',
    groupedExtractors: ['arte.tv', 'arte.tv:embed', 'arte.tv:playlist'],
  },
  {
    id: 'dtube',
    name: 'DTube',
    category: 'video',
    exampleDomain: 'd.tube',
    groupedExtractors: ['dtube'],
  },
  {
    id: 'dailywire',
    name: 'Daily Wire',
    category: 'video',
    exampleDomain: 'dailywire.com',
    groupedExtractors: ['dailywire', 'DailyWirePodcast'],
  },
];
